### ISSUE TITLE
bad design of input

### ISSUE THREAD

**Issue by danieltuzes** [chdemko/pandoc-latex-environment#3]
I try to use this script to automatize lots of conversation from html to latex via pandoc's markdown. In order to successfully achieve this, I convert the html's `<div>` items into latex environments. Unfortunately I cannot do this because I cannot add anything in a flexible way into the titleblock like

    latex-environment:
      myenv1: [myenv1classnameinhtml]
      myenv2: [myenv2classnameinhtml]
I have tried 3 ways to do it:
1. define key-value pair, but in this case I'll end up with the format `- 'myenv1: [myenv1classnameinhtml]'` which is not recognized by the filter
2. define in the header, but it is intended to use at the conversation from md, therefore it will be after the header or will be a `header-includes: |` inserted before.
3. modify the md's default template, but it's impossible to put anything into the titleblock from outside, or not documented.

My suggestion is to recognize the output of method 1 instead of the code expected, or the code I presented should be also correct for the script. I.e. the following should be (also) ok:

    latex-environment:
    - 'myenv1: [myenv1classnameinhtml]'
    - 'myenv2: [myenv2classnameinhtml]'

**Comment by chdemko** [comment]
My fault: the wiki page was not correct. Use

~~~
pandoc-latex-environment:
  myenv1: [myenv1classnameinhtml]
  myenv2: [myenv2classnameinhtml]
~~~

instead of

~~~
latex-environment:
  myenv1: [myenv1classnameinhtml]
  myenv2: [myenv2classnameinhtml]
~~~

See https://github.com/chdemko/pandoc-latex-environment/wiki

**Comment by danieltuzes** [comment]
For me, it seemed that `latex-environment:` also worked. Can you please give me an idea how to include it automatically in the .md header, when I make the conversation from html to markdown, then markdown to latex? I'd like to write into a header or template, or into the program call.

And thanks for replying :)

**Comment by chdemko** [comment]
You have to write your own filter to modify the `.md` header

Have a look to https://github.com/chdemko/pandoc-latex-tip. I modify the `.md` header to inject latex code

**Comment by chdemko** [comment]
The 0.0.4 version was using `latex-environment`

The 1.0.0 version use `pandoc-latex-environment`
