### ISSUE TITLE
Passing options to environments

### ISSUE THREAD

**Issue by HaoZeke** [chdemko/pandoc-latex-environment#5]
Hi. My specific usage is:

```tex
\begin[Type]{flashcard}{Title}
% content
\end{flashcard}
```

How could I pass title and type with this?

I noticed the source defines `title` to be equivalent to the `Type` given above, but I don't understand how to use it. Additionally there doesn't seem to be any method of passing `Title` as in the above example.

**Comment by chdemko** [comment]
Currently, this is not possible but you are kindly invited to propose a pull request for solving this issue

**Comment by chdemko** [comment]
Closing this issue as there is no PR
