### ISSUE TITLE
Creating commands with spans

### ISSUE THREAD

**Issue by adunning** [chdemko/pandoc-latex-environment#6]
It would be really brilliant if, along with support for creating environments, input such as `<span class="myclass">text</span>` could be used to create the command `\myclass{text}`.

**Comment by 3geek14** [comment]
I agree with @adunning !  I have a bit of inline formatting that I implement as `[text]{.myclass}` in the markdown, which turns into `{text}` in the LaTeX.  It'd be awesome if it could turn into either `\myclass{text}` or `\begin{myclass}{text}\end{myclass}`.

**Comment by chdemko** [comment]
Yuou can propose a pull request if you want.

**Comment by chdemko** [comment]
Closing this issue as there is no proposed PR
