### ISSUE TITLE
Command in latex environment

### ISSUE THREAD

**Issue by DCsunset** [chdemko/pandoc-latex-environment#8]
Hello.

I am using the outline environment.
But the command in the environment seems not working.

The code is shown as follows:

```markdown
---
pandoc-latex-environment:
  outline: [outline-class]
header-includes:
  \usepackage{outlines}
---

<div class="outline-class">
\1 Test
</div>
```

Besides, if I add a tab in front of `\1`,
an error occurs:

```
Error in $.blocks[0].c[1][0].c: cannot unpack array of length 4 into a tuple of length 2
```

It would be great if the `outline` environment could work.

**Comment by chdemko** [comment]
I don't have this issue.:

* what is your pdf-engine?
* what is your pandoc version
*  what is yout LaTeX distribution

**Comment by DCsunset** [comment]
After restarting my computer and compiling it again, this problem has gone.
There might be some invalid cache after failure.

Thanks for your reply.
